sudo: required
language: ruby
rvm: 2.5
addons:
  chrome: stable
branches:
  except:
    - static
    - gh-pages
script:
  - bundle exec rake wax:lunr
  - bundle exec jekyll build
  - bundle exec rake wax:test
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rake wax:push static; fi
deploy:
  - provider: s3
    access_key_id: $AWS_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: cul-s3-dlst-travis-devlib-staging
    region: us-west-2
    skip_cleanup: true
    local_dir: _site
    on:
      branch: staging
  - provider: s3
    access_key_id: $AWS_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: cul-s3-dlst-travis-devlib-prod
    region: us-west-2
    skip_cleanup: true
    local_dir: _site
    on:
      branch: master
