language: ruby
sudo: required
rvm: 2.4
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --allow-hash-href --disable-external
  - bundle exec rspec
branches:
  only:
    - master
