language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build -d _site/ldpd-devlib
  - bundle exec htmlproofer ./_site --only-4xx --check-html --allow-hash-href --assume-extension --disable-external
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - bundle exec rspec
