language: ruby
sudo: required
rvm: 2.4
addons:
  chrome: stable
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --allow-hash-href --disable-external
  - bundle exec rspec
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master
