title:        'Breaking the Code'
description:  The Developing Librarian Project

url:          ''
baseurl:      ''

permalink:    pretty

markdown:     kramdown
exclude:      [Gemfile*, vendor, spec, Rakefile, package*, README*]

collections:
    wposts:
      source: posts.json
      output: true
      layout: post
      lunr_index:
        content: true
        fields: ['title', 'author', 'categories', 'tags']
    pages:
      output: true

quoll:
  main:
    page: search
    terms: [git, design, omeka]

js:
  elasticlunr:
    version: 0.9.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js
  jquery:
    version: 3.2.1
    cdn: https://code.jquery.com/jquery-3.2.1.min.js
  enquire.js:
    version: 2.1.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/enquire.js/2.1.6/enquire.min.js
  superfish:
    version: 1.7.9
    cdn: https://cdnjs.cloudflare.com/ajax/libs/superfish/1.7.9/js/superfish.min.js
  jquery-migrate:
    version: 3.0.1
    cdn: https://code.jquery.com/jquery-migrate-3.0.1.min.js
