title:        Breaking the Code
description:  The Developing Librarian Project

version:      1.0.0
repo:         https://github.com/cul/ldpd-devlib.git

url:          ""
baseurl:      ""
gh-baseurl:   "/ldpd-devlib"

markdown:     kramdown
exclude:      [ Gemfile*, vendor, spec, Rakefile, package*, README* ]

collections:
    wposts:
      source: posts.yaml
      output: true
      directory: wposts
      layout: post
    pages:
      output: true

quoll:
  main:
    page: search.html
    terms:
      - git
      - design
      - omeka

# jscdn
scripts:
  - name: jquery
    src:  https://code.jquery.com/jquery-3.2.1.min.js
  - name: jquery-migrate
    src:  https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.min.js
  - name: lunr
    src:  https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.1.5/lunr.min.js
  - name: enquire.js
    src:  https://cdnjs.cloudflare.com/ajax/libs/enquire.js/2.1.6/enquire.min.js
  - name: superfish
    src:  https://cdnjs.cloudflare.com/ajax/libs/superfish/1.7.9/js/superfish.min.js
