title:        Breaking the Code
description:  The Developing Librarian Project

url:          ''
baseurl:      ''
gh-baseurl:   /ldpd-devlib

permalink:    pretty

markdown:     kramdown
exclude:      [Gemfile*, vendor, spec, Rakefile, package*, README*]

collections:
    wposts:
      source: posts.json
      output: true
      layout: post
    pages:
      output: true

quoll:
  main:
    page: search
    terms: [git, design, omeka]

js:
  jquery:
    version: 3.3.1
    cdn: https://code.jquery.com/jquery-3.3.1.min.js
  lunr:
    version: 2.1.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.1.6/lunr.min.js
  enquire.js:
    version: 2.1.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/enquire.js/2.1.6/enquire.min.js
  superfish:
    version: 1.7.9
    cdn: https://cdnjs.cloudflare.com/ajax/libs/superfish/1.7.9/js/superfish.min.js
  jquery-migrate:
    version: 3.0.1
    cdn: https://code.jquery.com/jquery-migrate-3.0.1.min.js
